// ktor-api/nextjs-admin-panel/src/app/admin/events/create/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { PageHeader, Button, Alert, LoadingOverlay } from '@/app/components/ui';
import { FormContainer, Input, Textarea, ImageUpload } from '@/app/components/forms';
import { api, ENDPOINTS } from '@/lib/api';
import { Event } from '@/lib/types';

export default function CreateEventPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [alert, setAlert] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    date: '',
    location: '',
    imageFile: null as File | null
  });
  
  const [errors, setErrors] = useState<Record<string, string>>({});

  const validateForm = () => {
    const newErrors: Record<string, string> = {};
    
    if (!formData.title.trim()) {
      newErrors.title = 'Title is required';
    }
    
    if (!formData.description.trim()) {
      newErrors.description = 'Description is required';
    }
    
    if (!formData.date) {
      newErrors.date = 'Date is required';
    } else {
      const eventDate = new Date(formData.date);
      const now = new Date();
      if (eventDate < now) {
        newErrors.date = 'Event date cannot be in the past';
      }
    }
    
    if (!formData.location.trim()) {
      newErrors.location = 'Location is required';
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateForm()) {
      return;
    }
    
    setLoading(true);
    setAlert(null);
    
    try {
      const submitData = new FormData();
      submitData.append('title', formData.title);
      submitData.append('description', formData.description);
      submitData.append('date', formData.date);
      submitData.append('location', formData.location);
      
      if (formData.imageFile) {
        submitData.append('image', formData.imageFile);
      }
      
      await api.postForm<Event>(ENDPOINTS.EVENTS, submitData);
      
      setAlert({ type: 'success', message: 'Event created successfully!' });
      
      // Redirect after a short delay
      setTimeout(() => {
        router.push('/admin/events');
      }, 1500);
      
    } catch (error) {
      console.error('Error creating event:', error);
      setAlert({ 
        type: 'error', 
        message: error instanceof Error ? error.message : 'Failed to create event' 
      });
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = () => {
    router.push('/admin/events');
  };

  return (
    <div className="space-y-6">
      <PageHeader 
        title="Create Event" 
        subtitle="Add a new event to the system"
      />
      
      {alert && (
        <Alert
          type={alert.type}
          message={alert.message}
          onClose={() => setAlert(null)}
        />
      )}
      
      <div className="max-w-2xl">
        <FormContainer onSubmit={handleSubmit}>
          <div className="space-y-6">
            <Input
              label="Event Title"
              value={formData.title}
              onChange={(value) => setFormData(prev => ({ ...prev, title: value }))}
              error={errors.title}
              placeholder="Enter event title"
              required
              disabled={loading}
            />
            
            <Textarea
              label="Description"
              value={formData.description}
              onChange={(value) => setFormData(prev => ({ ...prev, description: value }))}
              error={errors.description}
              placeholder="Enter event description"
              rows={4}
              required
              disabled={loading}
            />
            
            <Input
              label="Date & Time"
              type="datetime-local"
              value={formData.date}
              onChange={(value) => setFormData(prev => ({ ...prev, date: value }))}
              error={errors.date}
              required
              disabled={loading}
            />
            
            <Input
              label="Location"
              value={formData.location}
              onChange={(value) => setFormData(prev => ({ ...prev, location: value }))}
              error={errors.location}
              placeholder="Enter event location"
              required
              disabled={loading}
            />
            
            <ImageUpload
              label="Event Banner (Optional)"
              value={formData.imageFile ? URL.createObjectURL(formData.imageFile) : undefined}
              onChange={(file) => setFormData(prev => ({ ...prev, imageFile: file }))}
              accept="image/*"
              disabled={loading}
            />
            
            <div className="flex gap-4 pt-4">
              <Button
                type="submit"
                variant="primary"
                loading={loading}
                disabled={loading}
              >
                Create Event
              </Button>
              
              <Button
                type="button"
                variant="secondary"
                onClick={handleCancel}
                disabled={loading}
              >
                Cancel
              </Button>
            </div>
          </div>
        </FormContainer>
      </div>
      
      <LoadingOverlay show={loading} message="Creating event..." />
    </div>
  );
}

// ktor-api/svelte-admin-panel/src/routes/admin/events/create/+page.svelte
<script>
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';
	import FormContainer from '$lib/components/FormContainer.svelte';
	import Input from '$lib/components/Input.svelte';
	import Textarea from '$lib/components/Textarea.svelte';
	import Button from '$lib/components/Button.svelte';
	import Alert from '$lib/components/Alert.svelte';
	import Checkbox from '$lib/components/Checkbox.svelte';
	import ImageUpload from '$lib/components/ImageUpload.svelte';

	let title = '';
	let description = '';
	let date = '';
	let location = '';
	let maxAttendees = 0;
	let needsApproval = false;
	let image = null;
	let imagePreview = null;
	let loading = false;
	let message = '';
	let isError = false;
	async function createEvent() {
		loading = true;
		message = '';

		try {
			const formData = new FormData();
			formData.append('title', title);
			formData.append('description', description);
			formData.append('date', date);
			formData.append('location', location);
			formData.append('maxAttendees', maxAttendees);
			formData.append('needsApproval', needsApproval);

			if (image) {
				formData.append('image', image);
			}

			const result = await api.postForm(api.endpoints.EVENTS, formData);

			isError = false;
			message = result.message || 'Event created successfully!';
			setTimeout(() => {
				goto('/admin/events');
			}, 2000);
		} catch (error) {
			isError = true;
			message = `Error: ${error.message}`;
			console.error(error);
		} finally {
			loading = false;
		}
	}

	function goBack() {
		goto('/admin/events');
	}
</script>

<FormContainer
	title="Create New Event"
	subtitle="Fill in the details to create a new event"
	backButton={true}
	onBack={goBack}
	onSubmit={createEvent}
>
	{#if message}
		<Alert
			type={isError ? 'error' : 'success'}
			{message}
			dismissible={true}
			onDismiss={() => (message = '')}
		/>
	{/if}

	<Input
		label="Title"
		bind:value={title}
		placeholder="Enter event title"
		required={true}
		disabled={loading}
		id="title"
	/>

	<Input
		type="datetime-local"
		label="Date & Time"
		bind:value={date}
		required={true}
		disabled={loading}
		id="date"
	/>

	<Input
		label="Location"
		bind:value={location}
		placeholder="Enter event location"
		required={true}
		disabled={loading}
		id="location"
	/>

	<Input
		type="number"
		label="Max Attendees"
		bind:value={maxAttendees}
		placeholder="Enter maximum number of attendees"
		required={true}
		disabled={loading}
		id="maxAttendees"
		min="0"
	/>

	<Checkbox
		bind:checked={needsApproval}
		label="Registration needs admin approval"
		disabled={loading}
		id="needsApproval"
	/>

	<ImageUpload bind:image bind:imagePreview label="Event Image" disabled={loading} />

	<Textarea
		label="Description"
		bind:value={description}
		placeholder="Write event description here..."
		required={true}
		disabled={loading}
		rows={6}
		id="description"
	/>

	<div class="flex items-center gap-3 pt-4 border-t border-gray-200">
		<Button variant="secondary" onclick={goBack} disabled={loading}>Cancel</Button>
		<Button type="submit" {loading} disabled={loading} class="flex-1">
			{loading ? 'Creating Event...' : 'Create Event'}
		</Button>
	</div>
</FormContainer>
