// nextjs-admin-panel/src/app/admin/videos/[id]/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { YouTubeVideo } from '@/lib/types';
import { api } from '@/lib/api';
import { Button, NavigationHeader, Card } from '@/app/components/ui';

interface ApiResponse<T> {
  success: boolean;
  message: string;
  data: T;
}

interface FormData {
  title: string;
  description: string;
  videoUrl: string;
  thumbnailUrl: string;
  displayOrder: number;
  active: boolean;
}

function getYouTubeId(url: string) {
  const match = url.match(/(?:v=|youtu\.be\/|embed\/)([^&?\s]{11})/);
  return match ? match[1] : null;
}

function autoThumbnail(url: string) {
  const id = getYouTubeId(url);
  return id ? `https://img.youtube.com/vi/${id}/mqdefault.jpg` : '';
}

export default function EditVideoPage() {
  const router = useRouter();
  const params = useParams();
  const id = params.id as string;

  const [form, setForm] = useState<FormData>({
    title: '',
    description: '',
    videoUrl: '',
    thumbnailUrl: '',
    displayOrder: 0,
    active: true,
  });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetch = async () => {
      try {
        setLoading(true);
        const res = await api.youtubeVideos.getById(id) as ApiResponse<YouTubeVideo>;
        const v = res?.data;
        if (v) {
          setForm({
            title: v.title,
            description: v.description ?? '',
            videoUrl: v.videoUrl,
            thumbnailUrl: v.thumbnailUrl,
            displayOrder: v.displayOrder,
            active: v.active,
          });
        }
      } catch (e) {
        setError(e instanceof Error ? e.message : 'Failed to load video');
      } finally {
        setLoading(false);
      }
    };
    fetch();
  }, [id]);

  const handleChange = (field: keyof FormData, value: string | number | boolean) => {
    setForm(prev => {
      const updated = { ...prev, [field]: value };
      if (field === 'videoUrl' && typeof value === 'string') {
        const thumb = autoThumbnail(value);
        if (thumb) updated.thumbnailUrl = thumb;
      }
      return updated;
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.title.trim() || !form.videoUrl.trim()) {
      setError('Title and Video URL are required.');
      return;
    }

    try {
      setSaving(true);
      setError(null);
      await api.youtubeVideos.update(id, form);
      router.push('/admin/videos');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to update video');
    } finally {
      setSaving(false);
    }
  };

  const previewThumb = form.thumbnailUrl || autoThumbnail(form.videoUrl);

  if (loading) {
    return (
      <div className="space-y-6">
        <NavigationHeader
          title="Edit Video"
          breadcrumbs={[
            { label: 'Dashboard', href: '/admin/dashboard' },
            { label: 'Videos', href: '/admin/videos' },
            { label: 'Edit', current: true },
          ]}
        />
        <Card className="p-6 animate-pulse">
          <div className="space-y-4">
            {[1, 2, 3, 4].map(i => (
              <div key={i} className="h-10 bg-gray-200 rounded" />
            ))}
          </div>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <NavigationHeader
        title="Edit Video"
        subtitle="Update this YouTube video's details"
        breadcrumbs={[
          { label: 'Dashboard', href: '/admin/dashboard' },
          { label: 'Videos', href: '/admin/videos' },
          { label: 'Edit', current: true },
        ]}
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Form */}
        <div className="lg:col-span-2">
          <Card className="p-6">
            {error && (
              <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
                {error}
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-5">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Title <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={form.title}
                  onChange={e => handleChange('title', e.target.value)}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  YouTube URL <span className="text-red-500">*</span>
                </label>
                <input
                  type="url"
                  value={form.videoUrl}
                  onChange={e => handleChange('videoUrl', e.target.value)}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Thumbnail URL
                </label>
                <input
                  type="url"
                  value={form.thumbnailUrl}
                  onChange={e => handleChange('thumbnailUrl', e.target.value)}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Description
                </label>
                <textarea
                  value={form.description}
                  onChange={e => handleChange('description', e.target.value)}
                  rows={3}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Display Order
                  </label>
                  <input
                    type="number"
                    min={0}
                    value={form.displayOrder}
                    onChange={e => handleChange('displayOrder', parseInt(e.target.value) || 0)}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                  <p className="text-xs text-gray-400 mt-1">Lower numbers appear first.</p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
                  <div className="flex items-center gap-3 mt-2">
                    <button
                      type="button"
                      onClick={() => handleChange('active', !form.active)}
                      className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                        form.active ? 'bg-blue-600' : 'bg-gray-300'
                      }`}
                    >
                      <span
                        className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform shadow ${
                          form.active ? 'translate-x-6' : 'translate-x-1'
                        }`}
                      />
                    </button>
                    <span className="text-sm text-gray-700">
                      {form.active ? 'Active (visible in app)' : 'Hidden'}
                    </span>
                  </div>
                </div>
              </div>

              <div className="flex gap-3 pt-4 border-t border-gray-200">
                <Button type="submit" variant="primary" loading={saving}>
                  {saving ? 'Saving...' : 'Save Changes'}
                </Button>
                <Button type="button" variant="secondary" onClick={() => router.push('/admin/videos')}>
                  Cancel
                </Button>
              </div>
            </form>
          </Card>
        </div>

        {/* Preview */}
        <div>
          <Card className="p-4">
            <h3 className="text-sm font-semibold text-gray-700 mb-3">Preview</h3>
            <div className="bg-gray-900 rounded-lg overflow-hidden">
              {previewThumb ? (
                <div className="relative h-40">
                  <img src={previewThumb} alt="Thumbnail preview" className="w-full h-full object-cover" />
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="w-10 h-10 bg-red-600 rounded-full flex items-center justify-center">
                      <svg className="w-4 h-4 text-white ml-0.5" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M8 5v14l11-7z" />
                      </svg>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="h-40 flex items-center justify-center text-gray-500 text-sm">
                  Thumbnail preview
                </div>
              )}
            </div>
            {form.title && (
              <div className="mt-3">
                <p className="font-semibold text-gray-900 text-sm line-clamp-2">{form.title}</p>
                {form.description && (
                  <p className="text-xs text-gray-500 mt-1 line-clamp-2">{form.description}</p>
                )}
              </div>
            )}
            <div className="mt-3 flex gap-2 flex-wrap">
              <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                form.active ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'
              }`}>
                {form.active ? '● Active' : '○ Hidden'}
              </span>
              <span className="px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-700">
                Order: #{form.displayOrder}
              </span>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}

// ktor-api/svelte-admin-panel/src/routes/admin/posts/[id]/+page.svelte
<script>
    import { onMount } from 'svelte';
    import { page } from '$app/stores';
    import { goto } from '$app/navigation';
    import { fade, fly } from 'svelte/transition';
    import Cropper from 'cropperjs';
    import 'cropperjs/dist/cropper.css';

    let post = null;
    let title = '';
    let content = '';
    let headerImagePath = '';
    let image = null;
    let imagePreview = null;
    let loading = true;
    let saving = false;
    let errorMessage = '';
    let successMessage = '';
    let cropper;
    let imageElement;

    function getImageUrl(imagePath) {
        if (!imagePath) return null;
        return `http://localhost:8080/resources/uploads/images/${imagePath}`;
    }

    onMount(async () => {
        try {
            const postId = $page.params.id;
            const response = await fetch(`/api/posts/${postId}`);

            if (response.ok) {
                const data = await response.json();
                if (data.data && data.data.post) {
                    post = data.data.post;
                    title = post.title;
                    content = post.content;
                    headerImagePath = post.headerImagePath || '';
                    imagePreview = getImageUrl(headerImagePath);
                } else {
                    errorMessage = 'Post data not found in response';
                }
            } else {
                errorMessage = `Failed to fetch post. Status: ${response.status}`;
            }
        } catch (error) {
            errorMessage = `Error loading post: ${error.message}`;
            console.error(error);
        } finally {
            loading = false;
        }
    });

    async function updatePost() {
        saving = true;
        errorMessage = '';
        successMessage = '';

        try {
            const token = localStorage.getItem('authToken');
            const postId = $page.params.id;
            const formData = new FormData();
            formData.append('postId', postId);
            formData.append('title', title);
            formData.append('content', content);

            if (cropper && image) {
                const canvas = cropper.getCroppedCanvas({
                    width: 400,
                    height: 200
                });
                canvas.toBlob(async (blob) => {
                    formData.append('image', blob, 'cropped-image.jpg');
                    await sendFormData(formData, token);
                }, 'image/jpeg');
            } else {
                await sendFormData(formData, token);
            }
        } catch (error) {
            errorMessage = `Error updating post: ${error.message}`;
            console.error(error);
            saving = false;
        }
    }

    async function sendFormData(formData, token) {
        const response = await fetch('/api/posts/update', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${token}`
            },
            body: formData
        });

        if (response.ok) {
            successMessage = 'Post updated successfully!';
            setTimeout(() => goto('/admin/posts'), 1500);
        } else {
            const errorData = await response.json();
            errorMessage = errorData.message || 'Failed to update post';
        }
        saving = false;
    }

    function onFileSelected(e) {
        const file = e.target.files[0];
        if (file) {
            image = file;
            createImagePreview(file);
        }
    }

    function createImagePreview(file) {
        const reader = new FileReader();
        reader.onload = (e) => {
            imagePreview = e.target.result;
            if (cropper) {
                cropper.destroy();
            }
            setTimeout(() => {
                if (imageElement) {
                    cropper = new Cropper(imageElement, {
                        aspectRatio: 2 / 1,
                        viewMode: 1,
                    });
                }
            }, 100);
        };
        reader.readAsDataURL(file);
    }

    function goBack() {
        goto('/admin/posts');
    }

    function removeImage() {
        image = null;
        imagePreview = null;
        if (cropper) {
            cropper.destroy();
            cropper = null;
        }
        const fileInput = document.getElementById('image');
        if (fileInput) fileInput.value = '';
    }
</script>

<div class="p-8 w-full max-w-3xl mx-auto bg-gray-50 rounded-xl shadow-lg">
    <div class="mb-8 w-[70%]">
        <button on:click={goBack} class="flex items-center text-gray-600 hover:text-blue-600 transition-colors cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Posts
        </button>
    </div>

    <div class="flex items-center justify-between mb-6">
        <h1 class="text-3xl font-bold text-gray-800">Edit Post</h1>
    </div>

    {#if loading}
        <div class="flex justify-center items-center h-64" in:fade>
            <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-700"></div>
        </div>
    {:else if errorMessage && !post}
        <div in:fade class="bg-red-50 text-red-700 p-4 rounded-lg mb-6">
            <p>{errorMessage}</p>
            <button on:click={goBack} class="mt-3 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors">
                Return to Posts
            </button>
        </div>
    {:else if post}
        <div in:fly={{ y: 20, duration: 300 }} class="bg-white rounded-xl shadow-lg p-6 space-y-8">
            {#if successMessage}
                <div class="bg-green-50 text-green-700 p-4 rounded-lg mb-6 flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                    </svg>
                    <p>{successMessage}</p>
                </div>
            {/if}

            {#if errorMessage}
                <div class="bg-red-50 text-red-700 p-4 rounded-lg mb-6">
                    <p>{errorMessage}</p>
                </div>
            {/if}

            <form on:submit|preventDefault={updatePost} class="space-y-6">
                <div>
                    <label for="title" class="block text-sm font-medium text-gray-700 mb-1">Title</label>
                    <input type="text" id="title" bind:value={title} class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500" required disabled={saving}>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Featured Image</label>
                    <div class="bg-gray-50 rounded-lg overflow-hidden">
                        {#if imagePreview}
                            <div class="relative">
                                <img src={imagePreview} alt="Image preview" bind:this={imageElement} class="w-full">
                                <button type="button" on:click={removeImage} class="absolute top-2 right-2 bg-red-600 text-white rounded-full p-1 hover:bg-red-700 transition-colors cursor-pointer" title="Remove image">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                    </svg>
                                </button>
                            </div>
                        {:else}
                            <div class="border-2 border-dashed rounded-lg p-8 text-center cursor-pointer transition-colors" on:click={() => document.getElementById('image').click()}>
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                                </svg>
                                <p class="mt-3 text-sm text-gray-600">Click to select file</p>
                            </div>
                        {/if}
                    </div>
                    <input type="file" id="image" on:change={onFileSelected} accept="image/*" class="hidden">
                </div>

                <div>
                    <label for="content" class="block text-sm font-medium text-gray-700 mb-1">Content</label>
                    <textarea id="content" bind:value={content} class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500" rows="8" required disabled={saving}></textarea>
                </div>

                <div class="flex items-center pt-4 border-t border-gray-200">
                    <button type="button" on:click={goBack} class="px-6 py-3 bg-gray-100 text-gray-700 rounded-lg mr-4 hover:bg-gray-200 transition-colors cursor-pointer hover:shadow-md" disabled={saving}>
                        Cancel
                    </button>
                    <button type="submit" class="flex items-center justify-center px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex-1 cursor-pointer hover:shadow-md" disabled={saving}>
                        {#if saving}
                            <svg class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                            Saving Changes...
                        {:else}
                            Update Post
                        {/if}
                    </button>
                </div>
            </form>
        </div>
    {/if}
</div>
