// ktor-api/svelte-admin-panel/src/lib/components/Button.svelte
<script>
	let {
		variant = 'primary',
		size = 'md',
		disabled = false,
		loading = false,
		type = 'button',
		onclick = () => {},
		children,
		class: className = '',
		...props
	} = $props();

	const variants = {
		primary: 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm',
		secondary: 'bg-white hover:bg-gray-50 text-gray-900 border border-gray-300 shadow-sm',
		danger: 'bg-red-600 hover:bg-red-700 text-white shadow-sm',
		ghost: 'hover:bg-gray-100 text-gray-700',
		success: 'bg-green-600 hover:bg-green-700 text-white shadow-sm'
	};

	const sizes = {
		sm: 'px-3 py-1.5 text-sm',
		md: 'px-4 py-2 text-sm',
		lg: 'px-6 py-3 text-base'
	};

	const baseClasses = 'inline-flex items-center justify-center font-medium rounded-lg transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed';
</script>

<button
	{type}
	{disabled}
	class="{baseClasses} {variants[variant]} {sizes[size]} {className}"
	on:click={onclick}
	{...props}
>
	{#if loading}
		<svg class="animate-spin -ml-1 mr-2 h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
			<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
			<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
		</svg>
	{/if}
	{@render children()}
</button>

// nextjs-admin-panel/src/app/components/ui/Button.tsx
'use client';

import React from 'react';
import { ButtonProps } from '@/lib/types';
import { cn } from '@/lib/utils';

const variants = {
  primary: 'bg-[var(--color-accent)] text-white border-transparent hover:bg-[var(--color-accent-hover)]',
  secondary: 'bg-[var(--color-surface)] text-[var(--color-text)] border-[var(--color-border-med)] hover:bg-[var(--color-surface-alt)]',
  ghost: 'bg-transparent text-[var(--color-text-sub)] border-transparent hover:bg-[var(--color-surface-alt)]',
  danger: 'bg-[var(--color-danger-bg)] text-[var(--color-danger)] border-[rgba(220,38,38,0.2)] hover:bg-[#FECACA]',
  outline: 'bg-transparent text-[var(--color-accent)] border-[var(--color-accent)] hover:bg-[var(--color-accent-sub)]',
};

const sizes = {
  xs: 'px-[10px] py-[6px] text-[11px] max-sm:min-h-[40px]',
  sm: 'px-3 py-[7px] text-[12px] max-sm:min-h-[40px]',
  md: 'px-[14px] py-2 text-[13px]',
  lg: 'px-5 py-[10px] text-[14px]',
};

const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  icon,
  loading = false,
  disabled = false,
  onClick,
  children,
  className,
  type = 'button',
}) => (
  <button
    type={type}
    className={cn(
      'inline-flex items-center justify-center gap-1.5 rounded-[7px] border font-semibold transition-all duration-150 ease-out',
      'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-accent)]',
      'disabled:cursor-not-allowed disabled:opacity-50',
      variants[variant],
      sizes[size],
      className
    )}
    onClick={onClick}
    disabled={disabled || loading}
  >
    {loading ? (
      <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />
    ) : icon ? (
      <span className="shrink-0" aria-hidden="true">{icon}</span>
    ) : null}
    {children}
  </button>
);

export default Button;
