// ktor-api/svelte-admin-panel/src/lib/components/EmptyState.svelte
<script>
	let {
		icon,
		title,
		description,
		actionText = '',
		onAction = () => {},
		children
	} = $props();
</script>

<div class="text-center py-12">
	<div class="mx-auto h-24 w-24 text-gray-400 mb-4">
		{@render icon()}
	</div>
	
	<h3 class="text-xl font-semibold text-gray-700 mb-2">{title}</h3>
	<p class="text-gray-500 mb-6 max-w-sm mx-auto">{description}</p>
	
	{#if actionText}
		<button 
			on:click={onAction}
			class="inline-flex items-center px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
		>
			{actionText}
		</button>
	{/if}
	
	{#if children}
		<div class="mt-4">
			{@render children()}
		</div>
	{/if}
</div>

// nextjs-admin-panel/src/app/components/ui/EmptyState.tsx
'use client';

import React from 'react';
import { EmptyStateProps } from '@/lib/types';
import Button from './Button';
import { ImageIcon, PlusIcon } from '../icons/Icons';

const EmptyState: React.FC<EmptyStateProps & { actionLabel?: string }> = ({
  title,
  description,
  actionText,
  actionLabel,
  onAction,
  icon,
}) => (
  <div className="px-10 py-[60px] text-center">
    <div className="mx-auto mb-4 flex h-[52px] w-[52px] items-center justify-center rounded-[12px] bg-[var(--color-surface-alt)] text-[var(--color-text-muted)]">
      {icon || <ImageIcon />}
    </div>
    <h3 className="font-display text-[20px] font-normal text-[var(--color-text)]">{title}</h3>
    <p className="mx-auto mt-1 mb-5 max-w-sm text-[13px] leading-[1.5] text-[var(--color-text-sub)]">{description}</p>
    {(actionText || actionLabel) && onAction && (
      <Button variant="primary" size="md" icon={<PlusIcon />} onClick={onAction}>
        {actionLabel || actionText}
      </Button>
    )}
  </div>
);

export default EmptyState;
