// ktor-api/svelte-admin-panel/src/lib/components/MobileSidebar.svelte
<script>
	import { fly, fade } from 'svelte/transition';
	import Navigation from './Navigation.svelte';

	let { isOpen, onClose } = $props();
</script>

{#if isOpen}
	<button
		type="button"
		transition:fade={{duration: 150}}
		class="md:hidden fixed inset-0 z-20 bg-black bg-opacity-50"
		aria-label="Close sidebar overlay"
		tabindex="0"
		onclick={onClose}
		onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { onClose(); } }}
		style="background: none; border: none; padding: 0; margin: 0;"
	></button>
	
	<aside 
		transition:fly={{x: -300, duration: 200}}
		class="md:hidden fixed inset-y-0 left-0 z-30 w-64 bg-white dark:bg-gray-800 shadow-xl"
	>
		<div class="flex flex-col h-full">
			<div class="flex items-center justify-between h-16 px-4 border-b border-gray-200 dark:border-gray-700 bg-blue-600 dark:bg-blue-700">
				<div class="text-xl font-bold text-white">Admin Panel</div>
				<button onclick={onClose} class="p-1 text-white" aria-label="Close sidebar">
					<svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
					</svg>
				</button>
			</div>
			<Navigation onLinkClick={onClose} />
		</div>
	</aside>
{/if}

// ktor-api/nextjs-admin-panel/src/app/components/MobileSidebar.tsx
'use client';

import React from 'react';

interface MobileSidebarProps {
  isOpen: boolean;
  onClose: () => void;
}

const MobileSidebar: React.FC<MobileSidebarProps> = ({ isOpen, onClose }) => {
  return (
    <div
      className={`fixed inset-y-0 left-0 w-64 bg-gray-800 text-white p-4 transform ${isOpen ? 'translate-x-0' : '-translate-x-full'} transition-transform duration-300 ease-in-out md:hidden`}
    >
      <div className="flex justify-end mb-4">
        <button onClick={onClose} className="text-white focus:outline-none">
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
        </button>
      </div>
      <nav>
        <ul>
          <li className="mb-2"><a href="/admin/dashboard" className="hover:text-gray-300">Dashboard</a></li>
          <li className="mb-2"><a href="/admin/users" className="hover:text-gray-300">Users</a></li>
          <li className="mb-2"><a href="/admin/events" className="hover:text-gray-300">Events</a></li>
          <li className="mb-2"><a href="/admin/posts" className="hover:text-gray-300">Posts</a></li>
          <li className="mb-2"><a href="/admin/attendance" className="hover:text-gray-300">Attendance</a></li>
        </ul>
      </nav>
    </div>
  );
};

export default MobileSidebar;
