// ktor-api/nextjs-admin-panel/src/app/components/ui/Button.tsx
'use client';

import React from 'react';
import { ButtonProps } from '@/lib/types';
import { cn } from '@/lib/utils';
import { BUTTON_VARIANTS, BUTTON_SIZES } from '@/lib/constants';

const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  loading = false,
  disabled = false,
  onClick,
  children,
  className,
  type = 'button',
}) => {
  const baseClasses = 'inline-flex items-center justify-center font-medium rounded-md transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed hover:scale-105 active:scale-95 touch-target';
  
  const variantClasses = BUTTON_VARIANTS[variant];
  const sizeClasses = BUTTON_SIZES[size];

  return (
    <button
      type={type}
      className={cn(
        baseClasses,
        variantClasses,
        sizeClasses,
        loading && 'cursor-not-allowed',
        className
      )}
      onClick={onClick}
      disabled={disabled || loading}
    >
      {loading && (
        <svg
          className="animate-spin -ml-1 mr-2 h-4 w-4"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle
            className="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            strokeWidth="4"
          />
          <path
            className="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          />
        </svg>
      )}
      {children}
    </button>
  );
};

export default Button;

// ktor-api/svelte-admin-panel/src/lib/components/Button.svelte
<script>
	let {
		variant = 'primary',
		size = 'md',
		disabled = false,
		loading = false,
		type = 'button',
		onclick = () => {},
		children,
		class: className = '',
		...props
	} = $props();

	const variants = {
		primary: 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm',
		secondary: 'bg-white hover:bg-gray-50 text-gray-900 border border-gray-300 shadow-sm',
		danger: 'bg-red-600 hover:bg-red-700 text-white shadow-sm',
		ghost: 'hover:bg-gray-100 text-gray-700',
		success: 'bg-green-600 hover:bg-green-700 text-white shadow-sm'
	};

	const sizes = {
		sm: 'px-3 py-1.5 text-sm',
		md: 'px-4 py-2 text-sm',
		lg: 'px-6 py-3 text-base'
	};

	const baseClasses = 'inline-flex items-center justify-center font-medium rounded-lg transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed';
</script>

<button
	{type}
	{disabled}
	class="{baseClasses} {variants[variant]} {sizes[size]} {className}"
	on:click={onclick}
	{...props}
>
	{#if loading}
		<svg class="animate-spin -ml-1 mr-2 h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
			<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
			<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
		</svg>
	{/if}
	{@render children()}
</button>
