// nextjs-admin-panel/src/app/components/ui/Card.tsx
'use client';

import React from 'react';
import { CardProps } from '@/lib/types';
import { cn } from '@/lib/utils';

const Card: React.FC<CardProps> = ({
  children,
  hover = false,
  padding = '',
  className,
  onClick,
}) => (
  <div
    className={cn(
      'rounded-[10px] border border-[var(--color-border)] bg-[var(--color-surface)]',
      hover && 'transition-all duration-150 hover:border-[var(--color-border-med)] hover:shadow-[0_4px_16px_rgba(0,0,0,0.08)]',
      onClick && 'cursor-pointer',
      padding,
      className
    )}
    onClick={onClick}
  >
    {children}
  </div>
);

export default Card;

// ktor-api/svelte-admin-panel/src/lib/components/Card.svelte
<script>
	let {
		padding = 'p-6',
		shadow = 'shadow-sm',
		border = true,
		hover = false,
		children,
		class: className = '',
		...props
	} = $props();

	const baseClasses = 'bg-white rounded-xl transition-all duration-200';
	const borderClass = border ? 'border border-gray-200' : '';
	const hoverClass = hover ? 'hover:shadow-lg hover:scale-[1.01]' : '';
</script>

<div
	class="{baseClasses} {borderClass} {shadow} {hoverClass} {padding} {className}"
	{...props}
>
	{@render children()}
</div>
