// nextjs-admin-panel/src/app/components/forms/Checkbox.tsx
'use client';

import React from 'react';
import { CheckboxProps } from '@/lib/types';
import { cn } from '@/lib/utils';

const Checkbox: React.FC<CheckboxProps> = ({
  label,
  checked,
  onChange,
  error,
  disabled = false,
  className,
}) => {
  const checkboxId = React.useId();

  return (
    <div className={cn('space-y-1', className)}>
      <div className="flex items-center">
        <input
          id={checkboxId}
          type="checkbox"
          checked={checked}
          onChange={(e) => onChange(e.target.checked)}
          disabled={disabled}
          className={cn(
            'h-4 w-4 cursor-pointer text-blue-600 border-gray-300 rounded',
            'focus:ring-2 focus:ring-blue-500',
            'disabled:opacity-50 disabled:cursor-not-allowed',
            error && 'border-red-300 focus:ring-red-500'
          )}
          aria-invalid={error ? 'true' : 'false'}
          aria-describedby={error ? `${checkboxId}-error` : undefined}
        />
        {label && (
          <label
            htmlFor={checkboxId}
            className={cn(
              'ml-2 block cursor-pointer text-sm text-gray-700',
              disabled && 'opacity-50 cursor-not-allowed'
            )}
          >
            {label}
          </label>
        )}
      </div>
      {error && (
        <p
          id={`${checkboxId}-error`}
          className="text-sm text-red-600"
          role="alert"
        >
          {error}
        </p>
      )}
    </div>
  );
};

export default Checkbox;

// ktor-api/svelte-admin-panel/src/lib/components/Checkbox.svelte
<script>
	let {
		checked = $bindable(false),
		disabled = false,
		label = '',
		id = '',
		class: className = '',
		...props
	} = $props();
</script>

<div class="flex items-center space-x-3">
	<input 
		type="checkbox" 
		{id}
		{disabled}
		bind:checked
		class="w-5 h-5 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500 cursor-pointer disabled:cursor-not-allowed {className}"
		{...props}
	>
	{#if label}
		<label for={id} class="text-sm font-medium text-gray-700 cursor-pointer">
			{label}
		</label>
	{/if}
</div>
