// ktor-api/nextjs-admin-panel/src/app/components/forms/ImageUpload.tsx
'use client';

import React, { useRef, useState } from 'react';
import { ImageUploadProps } from '@/lib/types';
import { cn } from '@/lib/utils';
import { formatFileSize } from '@/lib/utils';
import { MAX_FILE_SIZE, ALLOWED_IMAGE_TYPES } from '@/lib/constants';

const ImageUpload: React.FC<ImageUploadProps> = ({
  label,
  value,
  onChange,
  error,
  accept = 'image/*',
  className,
  disabled = false,
}) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [dragOver, setDragOver] = useState(false);
  const [preview, setPreview] = useState<string | null>(value || null);

  const handleFileSelect = (file: File | null) => {
    if (!file) {
      onChange(null);
      setPreview(null);
      return;
    }

    // Validate file type
    if (!ALLOWED_IMAGE_TYPES.includes(file.type)) {
      return; // Could set an error here
    }

    // Validate file size
    if (file.size > MAX_FILE_SIZE) {
      return; // Could set an error here
    }

    onChange(file);

    // Create preview
    const reader = new FileReader();
    reader.onload = (e) => {
      setPreview(e.target?.result as string);
    };
    reader.readAsDataURL(file);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);

    const files = Array.from(e.dataTransfer.files);
    if (files.length > 0) {
      handleFileSelect(files[0]);
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
  };

  const handleClick = () => {
    if (!disabled) {
      fileInputRef.current?.click();
    }
  };

  const handleRemove = () => {
    handleFileSelect(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const inputId = React.useId();

  return (
    <div className={cn('space-y-1', className)}>
      {label && (
        <label
          htmlFor={inputId}
          className="block text-sm font-medium text-gray-700"
        >
          {label}
        </label>
      )}
      
      <div
        className={cn(
          'relative border-2 border-dashed rounded-lg p-6 transition-colors',
          disabled
            ? 'border-gray-200 bg-gray-50 cursor-not-allowed'
            : dragOver
            ? 'border-blue-400 bg-blue-50'
            : 'border-gray-300 hover:border-gray-400',
          error && 'border-red-300'
        )}
        onDrop={disabled ? undefined : handleDrop}
        onDragOver={disabled ? undefined : handleDragOver}
        onDragLeave={disabled ? undefined : handleDragLeave}
      >
        <input
          ref={fileInputRef}
          id={inputId}
          type="file"
          accept={accept}
          onChange={(e) => {
            const file = e.target.files?.[0] || null;
            handleFileSelect(file);
          }}
          className="hidden"
          disabled={disabled}
          aria-describedby={error ? `${inputId}-error` : undefined}
        />

        {preview ? (
          <div className="text-center">
            <img
              src={preview}
              alt="Preview"
              className="mx-auto h-32 w-32 object-cover rounded-lg mb-4"
            />
            <div className="flex justify-center space-x-2">
              <button
                type="button"
                onClick={handleClick}
                disabled={disabled}
                className={cn(
                  "text-sm transition-colors",
                  disabled
                    ? "text-gray-400 cursor-not-allowed"
                    : "text-blue-600 hover:text-blue-500"
                )}
              >
                Change Image
              </button>
              <button
                type="button"
                onClick={handleRemove}
                disabled={disabled}
                className={cn(
                  "text-sm transition-colors",
                  disabled
                    ? "text-gray-400 cursor-not-allowed"
                    : "text-red-600 hover:text-red-500"
                )}
              >
                Remove
              </button>
            </div>
          </div>
        ) : (
          <div className="text-center">
            <svg
              className="mx-auto h-12 w-12 text-gray-400"
              stroke="currentColor"
              fill="none"
              viewBox="0 0 48 48"
            >
              <path
                d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02"
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
            <div className="mt-4">
              <button
                type="button"
                onClick={handleClick}
                disabled={disabled}
                className={cn(
                  "font-medium transition-colors",
                  disabled
                    ? "text-gray-400 cursor-not-allowed"
                    : "text-blue-600 hover:text-blue-500"
                )}
              >
                Upload an image
              </button>
              <p className={cn(
                "text-sm mt-1",
                disabled ? "text-gray-400" : "text-gray-500"
              )}>
                {disabled ? "Upload disabled" : "or drag and drop"}
              </p>
            </div>
            <p className="text-xs text-gray-500 mt-2">
              PNG, JPG, GIF up to {formatFileSize(MAX_FILE_SIZE)}
            </p>
          </div>
        )}
      </div>

      {error && (
        <p
          id={`${inputId}-error`}
          className="text-sm text-red-600"
          role="alert"
        >
          {error}
        </p>
      )}
    </div>
  );
};

export default ImageUpload;

// ktor-api/svelte-admin-panel/src/lib/components/ImageUpload.svelte
<script>
	import Button from './Button.svelte';
	
	let {
		image = $bindable(null),
		imagePreview = $bindable(null),
		label = 'Image',
		accept = 'image/*',
		disabled = false,
		dragText = 'Drag and drop image here, or click to select file',
		supportText = 'PNG, JPG, GIF up to 5MB'
	} = $props();

	let dragActive = false;
	let fileInput;

	function onFileSelected(e) {
		const file = e.target.files[0];
		if (file) {
			image = file;
			createImagePreview(file);
		}
	}
	
	function createImagePreview(file) {
		const reader = new FileReader();
		reader.onload = (e) => {
			imagePreview = e.target.result;
		};
		reader.readAsDataURL(file);
	}
	
	function handleDragEnter(e) {
		e.preventDefault();
		dragActive = true;
	}
	
	function handleDragLeave(e) {
		e.preventDefault();
		dragActive = false;
	}
	
	function handleDrop(e) {
		e.preventDefault();
		dragActive = false;
		
		if (e.dataTransfer.files.length) {
			const file = e.dataTransfer.files[0];
			if (file.type.startsWith('image/')) {
				image = file;
				createImagePreview(file);
			}
		}
	}
	
	function removeImage() {
		image = null;
		imagePreview = null;
		if (fileInput) fileInput.value = '';
	}
</script>

<div class="space-y-2">
	<label class="block text-sm font-medium text-gray-700">{label}</label>
	
	{#if imagePreview}
		<div class="relative rounded-lg overflow-hidden bg-gray-100">
			<img src={imagePreview} alt="Image preview" class="w-full h-64 object-cover">
			<Button 
				variant="danger"
				size="sm"
				onclick={removeImage}
				class="absolute top-2 right-2 !p-1 !rounded-full"
				title="Remove image"
			>
				<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
				</svg>
			</Button>
		</div>
	{:else}
		<!-- Drag and Drop Zone -->
		<div 
			class="border-2 border-dashed rounded-lg p-8 text-center cursor-pointer transition-colors hover:bg-gray-50"
			class:border-gray-300={!dragActive} 
			class:border-indigo-500={dragActive}
			class:bg-indigo-50={dragActive}
			class:opacity-50={disabled}
			class:cursor-not-allowed={disabled}
			on:dragenter={handleDragEnter}
			on:dragover|preventDefault
			on:dragleave={handleDragLeave}
			on:drop={handleDrop}
			on:click={() => !disabled && fileInput.click()}
			role="button"
			tabindex="0"
		>
			<svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
			</svg>
			<p class="mt-3 text-sm text-gray-600">{dragText}</p>
			<p class="mt-1 text-xs text-gray-500">{supportText}</p>
		</div>
	{/if}
	
	<input 
		bind:this={fileInput}
		type="file" 
		on:change={onFileSelected} 
		{accept}
		{disabled}
		class="hidden"
	>
</div>
