// ktor-api/svelte-admin-panel/src/lib/components/Modal.svelte
<script>
	import { fade, fly } from 'svelte/transition';
	
	let {
		show = false,
		title = '',
		onClose = () => {},
		children,
		size = 'md'
	} = $props();

	const sizes = {
		sm: 'max-w-sm',
		md: 'max-w-md',
		lg: 'max-w-lg',
		xl: 'max-w-xl'
	};

	function handleBackdropClick(e) {
		if (e.target === e.currentTarget) {
			onClose();
		}
	}
</script>

{#if show}
	<div 
		class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4" 
		transition:fade={{ duration: 200 }}
		on:click={handleBackdropClick}
		role="dialog"
		aria-modal="true"
	>
		<div 
			class="bg-white rounded-xl shadow-xl w-full {sizes[size]} mx-4"
			in:fly={{ y: 20, duration: 200 }}
		>
			{#if title}
				<div class="px-6 py-4 border-b border-gray-200">
					<h3 class="text-lg font-semibold text-gray-900">{title}</h3>
				</div>
			{/if}
			
			<div class="p-6">
				{@render children()}
			</div>
		</div>
	</div>
{/if}

// ktor-api/nextjs-admin-panel/src/app/components/ui/Modal.tsx
'use client';

import React, { useEffect } from 'react';
import { ModalProps } from '@/lib/types';
import { cn } from '@/lib/utils';
import { MODAL_SIZES } from '@/lib/constants';

const Modal: React.FC<ModalProps> = ({
  show,
  title,
  size = 'md',
  onClose,
  children,
}) => {
  // Handle escape key press
  useEffect(() => {
    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        onClose();
      }
    };

    if (show) {
      document.addEventListener('keydown', handleEscape);
      // Prevent body scroll when modal is open
      document.body.style.overflow = 'hidden';
    }

    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = 'unset';
    };
  }, [show, onClose]);

  if (!show) return null;

  const sizeClasses = MODAL_SIZES[size];

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto animate-in fade-in" style={{ animationDuration: '200ms' }}>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black bg-opacity-50 transition-opacity duration-200"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="flex min-h-full items-center justify-center p-4">
        <div
          className={cn(
            'relative w-full bg-white rounded-lg shadow-xl animate-in scale-in',
            sizeClasses
          )}
          style={{ animationDuration: '300ms', animationDelay: '100ms' }}
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900">
              {title}
            </h3>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600 transition-colors"
              aria-label="Close modal"
            >
              <svg
                className="w-6 h-6"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
          
          {/* Content */}
          <div className="p-6">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Modal;
