// ktor-api/svelte-admin-panel/src/routes/admin/attendance/reports/+page.svelte
<script>
    import { onMount } from 'svelte';
    import PageHeader from '$lib/components/PageHeader.svelte';
    import Card from '$lib/components/Card.svelte';
    import { EventType } from '$lib/types/attendance';
    
    let selectedEventType = EventType.EVENT;
    let dateRange = {
        start: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // Last 30 days
        end: new Date().toISOString().split('T')[0] // Today
    };
    
    function updateEventType(type) {
        selectedEventType = type;
        // Here you would fetch reports for the selected event type
    }
    
    function updateDateRange() {
        // Here you would fetch reports for the updated date range
    }
    
    function exportReport(format) {
        // Here you would implement export functionality
        alert(`Exporting ${selectedEventType} report in ${format} format`);
    }
</script>

<PageHeader title="Attendance Reports" backLink="/admin/attendance" />

<div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
    <div class="lg:col-span-1">
        <Card>
            <div class="p-6">
                <h3 class="text-lg font-semibold mb-4">Report Filters</h3>
                
                <div class="mb-4">
                    <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Event Type</label>
                    <div class="flex flex-col space-y-2">
                        <label class="inline-flex items-center">
                            <input 
                                type="radio" 
                                class="form-radio" 
                                name="eventType" 
                                value={EventType.EVENT} 
                                checked={selectedEventType === EventType.EVENT}
                                on:change={() => updateEventType(EventType.EVENT)}
                            />
                            <span class="ml-2">Events</span>
                        </label>
                        <label class="inline-flex items-center">
                            <input 
                                type="radio" 
                                class="form-radio" 
                                name="eventType" 
                                value={EventType.SERVICE} 
                                checked={selectedEventType === EventType.SERVICE}
                                on:change={() => updateEventType(EventType.SERVICE)}
                            />
                            <span class="ml-2">Services</span>
                        </label>
                        <label class="inline-flex items-center">
                            <input 
                                type="radio" 
                                class="form-radio" 
                                name="eventType" 
                                value={EventType.KIDS_SERVICE} 
                                checked={selectedEventType === EventType.KIDS_SERVICE}
                                on:change={() => updateEventType(EventType.KIDS_SERVICE)}
                            />
                            <span class="ml-2">Kids Services</span>
                        </label>
                    </div>
                </div>
                
                <div class="mb-4">
                    <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Date Range</label>
                    <div class="space-y-2">
                        <div>
                            <label class="block text-xs text-gray-500 dark:text-gray-400 mb-1">Start Date</label>
                            <input 
                                type="date" 
                                class="w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-800"
                                bind:value={dateRange.start}
                                on:change={updateDateRange}
                            />
                        </div>
                        <div>
                            <label class="block text-xs text-gray-500 dark:text-gray-400 mb-1">End Date</label>
                            <input 
                                type="date" 
                                class="w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-800"
                                bind:value={dateRange.end}
                                on:change={updateDateRange}
                            />
                        </div>
                    </div>
                </div>
                
                <div>
                    <h4 class="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Export Report</h4>
                    <div class="flex space-x-2">
                        <button 
                            on:click={() => exportReport('csv')}
                            class="px-3 py-2 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-md hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
                        >
                            CSV
                        </button>
                        <button 
                            on:click={() => exportReport('pdf')}
                            class="px-3 py-2 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-md hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
                        >
                            PDF
                        </button>
                    </div>
                </div>
            </div>
        </Card>
    </div>
    
    <div class="lg:col-span-2">
        <Card>
            <div class="p-6">
                <h3 class="text-lg font-semibold mb-4">Attendance Summary</h3>
                
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
                    <div class="bg-blue-50 dark:bg-blue-900 p-4 rounded-lg">
                        <div class="text-sm text-blue-600 dark:text-blue-300 mb-1">Total Attendees</div>
                        <div class="text-2xl font-bold">0</div>
                    </div>
                    <div class="bg-green-50 dark:bg-green-900 p-4 rounded-lg">
                        <div class="text-sm text-green-600 dark:text-green-300 mb-1">Average Attendance</div>
                        <div class="text-2xl font-bold">0</div>
                    </div>
                    <div class="bg-purple-50 dark:bg-purple-900 p-4 rounded-lg">
                        <div class="text-sm text-purple-600 dark:text-purple-300 mb-1">Check-in Rate</div>
                        <div class="text-2xl font-bold">0%</div>
                    </div>
                    <div class="bg-yellow-50 dark:bg-yellow-900 p-4 rounded-lg">
                        <div class="text-sm text-yellow-600 dark:text-yellow-300 mb-1">No-Show Rate</div>
                        <div class="text-2xl font-bold">0%</div>
                    </div>
                </div>
                
                <div class="mb-6">
                    <h4 class="text-md font-medium mb-2">Attendance Trend</h4>
                    <div class="bg-gray-100 dark:bg-gray-800 h-64 rounded-lg flex items-center justify-center">
                        <p class="text-gray-500 dark:text-gray-400">Chart will be displayed here</p>
                    </div>
                </div>
                
                <div>
                    <h4 class="text-md font-medium mb-2">Top Events by Attendance</h4>
                    <div class="overflow-x-auto">
                        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                            <thead>
                                <tr>
                                    <th class="px-6 py-3 bg-gray-50 dark:bg-gray-800 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                                        Name
                                    </th>
                                    <th class="px-6 py-3 bg-gray-50 dark:bg-gray-800 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                                        Date
                                    </th>
                                    <th class="px-6 py-3 bg-gray-50 dark:bg-gray-800 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                                        Attendees
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-800">
                                <tr>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-200">
                                        No data available
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                        -
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                        -
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </Card>
    </div>
</div>

// ktor-api/nextjs-admin-panel/src/app/admin/attendance/reports/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import { AttendanceRecord, AttendanceStatus, EventType } from '@/lib/types';
import { 
  PageHeader, 
  Card, 
  Button, 
  EmptyState, 
  LoadingOverlay,
  Alert
} from '@/app/components/ui';
import { Input } from '@/app/components/forms';
import { useApiCall } from '@/app/hooks';
import { api } from '@/lib/api';
import { cn } from '@/lib/utils';

interface AttendanceFilters {
  startDate: string;
  endDate: string;
  eventType: EventType | 'all';
  status: AttendanceStatus | 'all';
  searchTerm: string;
}

interface AttendanceStats {
  totalRecords: number;
  byStatus: Record<AttendanceStatus, number>;
  byEventType: Record<EventType, number>;
  byDate: Record<string, number>;
}

const AttendanceReportsPage: React.FC = () => {
  const [filters, setFilters] = useState<AttendanceFilters>({
    startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 30 days ago
    endDate: new Date().toISOString().split('T')[0], // today
    eventType: 'all',
    status: 'all',
    searchTerm: '',
  });

  const [attendanceData, setAttendanceData] = useState<AttendanceRecord[]>([]);
  const [stats, setStats] = useState<AttendanceStats | null>(null);
  const [alert, setAlert] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  const { 
    execute: fetchAttendanceByDateRange, 
    loading: loadingData 
  } = useApiCall(api.attendance.getByDateRange);

  const { 
    execute: exportAttendanceData, 
    loading: exporting 
  } = useApiCall(api.attendance.exportData);

  useEffect(() => {
    loadAttendanceData();
  }, [filters.startDate, filters.endDate, filters.eventType]);

  const loadAttendanceData = async () => {
    try {
      const eventTypeParam = filters.eventType === 'all' ? undefined : filters.eventType;
      const response = await fetchAttendanceByDateRange(
        filters.startDate, 
        filters.endDate, 
        eventTypeParam
      );
      
      if (response && response.success) {
        setAttendanceData(response.data);
        calculateStats(response.data);
      }
    } catch (error) {
      console.error('Failed to load attendance data:', error);
      setAlert({ type: 'error', message: 'Failed to load attendance data' });
    }
  };

  const calculateStats = (data: AttendanceRecord[]) => {
    const stats: AttendanceStats = {
      totalRecords: data.length,
      byStatus: {
        [AttendanceStatus.CHECKED_IN]: 0,
        [AttendanceStatus.CHECKED_OUT]: 0,
        [AttendanceStatus.NO_SHOW]: 0,
        [AttendanceStatus.EMERGENCY]: 0,
      },
      byEventType: {
        [EventType.EVENT]: 0,
        [EventType.SERVICE]: 0,
        [EventType.KIDS_SERVICE]: 0,
      },
      byDate: {},
    };

    data.forEach(record => {
      // Count by status
      stats.byStatus[record.status]++;
      
      // Count by event type
      stats.byEventType[record.eventType]++;
      
      // Count by date
      const date = new Date(record.timestamp).toISOString().split('T')[0];
      stats.byDate[date] = (stats.byDate[date] || 0) + 1;
    });

    setStats(stats);
  };

  const handleFilterChange = (key: keyof AttendanceFilters, value: string) => {
    setFilters(prev => ({ ...prev, [key]: value }));
  };

  const handleExport = async () => {
    try {
      const exportFilters = {
        startDate: filters.startDate,
        endDate: filters.endDate,
        ...(filters.eventType !== 'all' && { eventType: filters.eventType }),
        ...(filters.status !== 'all' && { status: filters.status }),
        ...(filters.searchTerm && { search: filters.searchTerm }),
      };

      const response = await exportAttendanceData(exportFilters);
      
      if (response && response.success) {
        // Create and download the file
        const blob = new Blob([response.data], { type: 'text/csv' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `attendance-report-${filters.startDate}-to-${filters.endDate}.csv`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
        
        setAlert({ type: 'success', message: 'Report exported successfully' });
      }
    } catch (error) {
      console.error('Failed to export data:', error);
      setAlert({ type: 'error', message: 'Failed to export report' });
    }
  };

  const filteredData = attendanceData.filter(record => {
    const matchesStatus = filters.status === 'all' || record.status === filters.status;
    const matchesSearch = !filters.searchTerm || 
      record.attendeeName.toLowerCase().includes(filters.searchTerm.toLowerCase()) ||
      record.eventName.toLowerCase().includes(filters.searchTerm.toLowerCase());
    
    return matchesStatus && matchesSearch;
  });

  const getStatusLabel = (status: AttendanceStatus) => {
    switch (status) {
      case AttendanceStatus.CHECKED_IN:
        return 'Checked In';
      case AttendanceStatus.CHECKED_OUT:
        return 'Checked Out';
      case AttendanceStatus.NO_SHOW:
        return 'No Show';
      case AttendanceStatus.EMERGENCY:
        return 'Emergency';
      default:
        return 'Unknown';
    }
  };

  const getEventTypeLabel = (eventType: EventType) => {
    switch (eventType) {
      case EventType.EVENT:
        return 'Events';
      case EventType.SERVICE:
        return 'Services';
      case EventType.KIDS_SERVICE:
        return 'Kids Services';
      default:
        return 'Unknown';
    }
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Attendance Reports"
        subtitle="Generate and export attendance reports with filtering capabilities"
      >
        <Button
          variant="primary"
          onClick={handleExport}
          loading={exporting}
          disabled={filteredData.length === 0}
        >
          Export Report
        </Button>
      </PageHeader>

      {alert && (
        <Alert
          type={alert.type}
          message={alert.message}
          onClose={() => setAlert(null)}
        />
      )}

      {/* Filters */}
      <Card className="p-6">
        <h3 className="text-lg font-medium text-gray-900 mb-4">Report Filters</h3>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div>
            <Input
              label="Start Date"
              type="date"
              value={filters.startDate}
              onChange={(value) => handleFilterChange('startDate', value)}
            />
          </div>
          
          <div>
            <Input
              label="End Date"
              type="date"
              value={filters.endDate}
              onChange={(value) => handleFilterChange('endDate', value)}
            />
          </div>
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Event Type
            </label>
            <select
              value={filters.eventType}
              onChange={(e) => handleFilterChange('eventType', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="all">All Types</option>
              <option value={EventType.EVENT}>Events</option>
              <option value={EventType.SERVICE}>Services</option>
              <option value={EventType.KIDS_SERVICE}>Kids Services</option>
            </select>
          </div>
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Status
            </label>
            <select
              value={filters.status}
              onChange={(e) => handleFilterChange('status', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="all">All Status</option>
              <option value={AttendanceStatus.CHECKED_IN}>Checked In</option>
              <option value={AttendanceStatus.CHECKED_OUT}>Checked Out</option>
              <option value={AttendanceStatus.NO_SHOW}>No Show</option>
              <option value={AttendanceStatus.EMERGENCY}>Emergency</option>
            </select>
          </div>
          
          <div className="md:col-span-2">
            <Input
              label="Search"
              placeholder="Search by attendee or event name..."
              value={filters.searchTerm}
              onChange={(value) => handleFilterChange('searchTerm', value)}
            />
          </div>
        </div>

        <div className="mt-4 flex justify-end">
          <Button
            variant="secondary"
            onClick={loadAttendanceData}
            loading={loadingData}
          >
            Apply Filters
          </Button>
        </div>
      </Card>

      {/* Statistics Overview */}
      {stats && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Status Statistics */}
          <Card className="p-6">
            <h3 className="text-lg font-medium text-gray-900 mb-4">By Status</h3>
            <div className="space-y-3">
              {Object.entries(stats.byStatus).map(([status, count]) => (
                <div key={status} className="flex justify-between items-center">
                  <span className="text-sm text-gray-600">
                    {getStatusLabel(status as AttendanceStatus)}
                  </span>
                  <span className="font-medium">{count}</span>
                </div>
              ))}
            </div>
          </Card>

          {/* Event Type Statistics */}
          <Card className="p-6">
            <h3 className="text-lg font-medium text-gray-900 mb-4">By Event Type</h3>
            <div className="space-y-3">
              {Object.entries(stats.byEventType).map(([eventType, count]) => (
                <div key={eventType} className="flex justify-between items-center">
                  <span className="text-sm text-gray-600">
                    {getEventTypeLabel(eventType as EventType)}
                  </span>
                  <span className="font-medium">{count}</span>
                </div>
              ))}
            </div>
          </Card>

          {/* Total Records */}
          <Card className="p-6">
            <h3 className="text-lg font-medium text-gray-900 mb-4">Summary</h3>
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-sm text-gray-600">Total Records</span>
                <span className="font-medium text-2xl text-blue-600">{stats.totalRecords}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm text-gray-600">Filtered Results</span>
                <span className="font-medium text-lg">{filteredData.length}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm text-gray-600">Date Range</span>
                <span className="text-sm font-medium">
                  {Object.keys(stats.byDate).length} days
                </span>
              </div>
            </div>
          </Card>
        </div>
      )}

      {/* Data Preview */}
      <Card className="p-6">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-lg font-medium text-gray-900">Data Preview</h3>
          <span className="text-sm text-gray-500">
            Showing {filteredData.length} of {attendanceData.length} records
          </span>
        </div>

        <div className="relative">
          <LoadingOverlay show={loadingData} />
          
          {filteredData.length === 0 ? (
            <EmptyState
              title="No data found"
              description="No attendance records match your current filters"
              actionText="Clear Filters"
              onAction={() => {
                setFilters({
                  startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
                  endDate: new Date().toISOString().split('T')[0],
                  eventType: 'all',
                  status: 'all',
                  searchTerm: '',
                });
              }}
            />
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Attendee
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Event
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Type
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Status
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Date
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {filteredData.slice(0, 50).map((record) => (
                    <tr key={record.id} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {record.attendeeName}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {record.eventName}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {getEventTypeLabel(record.eventType)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={cn(
                          'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
                          record.status === AttendanceStatus.CHECKED_IN && 'bg-green-100 text-green-800',
                          record.status === AttendanceStatus.CHECKED_OUT && 'bg-blue-100 text-blue-800',
                          record.status === AttendanceStatus.NO_SHOW && 'bg-red-100 text-red-800',
                          record.status === AttendanceStatus.EMERGENCY && 'bg-orange-100 text-orange-800'
                        )}>
                          {getStatusLabel(record.status)}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {new Date(record.timestamp).toLocaleDateString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              
              {filteredData.length > 50 && (
                <div className="px-6 py-3 bg-gray-50 text-center text-sm text-gray-500">
                  Showing first 50 records. Export to see all {filteredData.length} records.
                </div>
              )}
            </div>
          )}
        </div>
      </Card>
    </div>
  );
};

export default AttendanceReportsPage;
