// nextjs-admin-panel/src/app/login/page.tsx
'use client';

import { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '../context/AuthContext';

function LoginContent() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const { login } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();

  useEffect(() => {
    if (searchParams.get('registered') === 'true') {
      setSuccess('Registration successful! Please sign in.');
    }
  }, [searchParams]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');

    try {
      // Use the Next.js proxy route which forwards to auth-service (port 8081)
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      });

      const response = await res.json();
      console.log('🔐 Login response:', response);

      if (response?.success && response?.data?.token) {
        console.log('✅ Login successful, token received');
        login(response.data.token);
        router.push('/admin/dashboard');
      } else {
        console.log('❌ Login failed: No token in response', response);
        setError(response?.message || 'Login failed: Invalid credentials.');
      }
    } catch (err: unknown) {
      console.log('🔴 Login error:', err);
      setError(err instanceof Error ? err.message : 'An unexpected error occurred.');
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen w-full bg-gradient-to-br from-indigo-50 to-white">
      <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
        <h1 className="text-2xl font-bold text-center mb-6">Admin Login</h1>

        {success && (
          <div className="mb-4 p-3 bg-green-100 text-green-700 rounded border border-green-200 text-sm">
            {success}
          </div>
        )}

        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label htmlFor="email" className="block text-gray-700 text-sm font-bold mb-2">
              Email:
            </label>
            <input
              type="email"
              id="email"
              className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>
          <div className="mb-6">
            <label htmlFor="password" className="block text-gray-700 text-sm font-bold mb-2">
              Password:
            </label>
            <input
              type="password"
              id="password"
              className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>
          {error && <p className="text-red-500 text-xs italic mb-4">{error}</p>}
          <div className="flex flex-col gap-4">
            <button
              type="submit"
              className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full"
            >
              Sign In
            </button>
            <div className="text-center text-sm">
              <span className="text-gray-600">Don't have an account? </span>
              <Link href="/register" className="text-blue-500 hover:text-blue-700 font-semibold">
                Sign up
              </Link>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}

export default function LoginPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <LoginContent />
    </Suspense>
  );
}

// ktor-api/svelte-admin-panel/src/routes/login/+page.svelte
<script>
    import { goto } from '$app/navigation';

    let email = '';
    let password = '';
    let errorMessage = '';

    async function login() {
        try {
            const response = await fetch('/api/auth/login', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ email, password })
            });

            if (response.ok) {
                const data = await response.json();
                if (data.success) {
                    localStorage.setItem('authToken', data.data.token);
                    goto('/admin');
                } else {
                    errorMessage = data.message;
                }
            } else {
                errorMessage = 'Login failed. Please check your credentials.';
            }
        } catch (error) {
            errorMessage = 'An error occurred during login.';
            console.error(error);
        }
    }
</script>

<div class="flex items-center justify-center h-screen">
    <div class="w-full max-w-md p-8 space-y-6 bg-white rounded-lg shadow-md">
        <h1 class="text-2xl font-bold text-center">Admin Login</h1>
        <form on:submit|preventDefault={login}>
            <div>
                <label for="email" class="text-sm font-medium">Email</label>
                <input type="text" id="email" bind:value={email} class="w-full px-3 py-2 mt-1 border rounded-md" required>
            </div>
            <div>
                <label for="password" class="text-sm font-medium">Password</label>
                <input type="password" id="password" bind:value={password} class="w-full px-3 py-2 mt-1 border rounded-md" required>
            </div>
            {#if errorMessage}
                <p class="text-sm text-red-500">{errorMessage}</p>
            {/if}
            <button type="submit" class="w-full px-4 py-2 mt-4 font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700">
                Login
            </button>
        </form>
    </div>
</div>
